# Generated by Django 2.1.4 on 2019-01-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='isCheap',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='isHot',
            field=models.IntegerField(null=True),
        ),
    ]
