# Generated by Django 2.1.4 on 2019-01-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190116_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
