# Generated by Django 2.1.4 on 2019-01-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190117_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='name',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='on_sale',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='stock',
            new_name='sort',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='location',
        ),
        migrations.RemoveField(
            model_name='record',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='sale_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='withdraw_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='withdraw_num',
        ),
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='purchase_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='sale_num',
            field=models.IntegerField(null=True),
        ),
    ]
