# Generated by Django 2.1.4 on 2019-01-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190117_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='preserve',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
