# Generated by Django 2.1.4 on 2019-01-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_goods_preserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='isHot',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='preserve',
        ),
    ]
