# Generated by Django 2.1.4 on 2019-01-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190119_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='withdraw',
        ),
        migrations.AddField(
            model_name='record',
            name='withdraw_num',
            field=models.IntegerField(null=True),
        ),
    ]
