# Generated by Django 2.1.4 on 2019-01-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190119_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='isCheap',
        ),
        migrations.AddField(
            model_name='goods',
            name='lower',
            field=models.FloatField(default=0),
        ),
    ]
